package com.pm.billingservice.service;

import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.YearMonth;
import java.util.*;

/**
 * Report Generation Service for MoveInSync
 * Generates auditable reports for:
 * 1. Clients - Monthly summary of all trips and vendor payments
 * 2. Vendors - Detailed statements of payable trips and incentives
 * 3. Employees - Summary of earned incentives
 * 
 * As per MoveInSync requirements: Reports must be clear, reliable, and auditable
 */
@Service
public class ReportGenerationService {
    
    /**
     * Generate Client Report
     * Shows: Total trips, Total cost, Vendor-wise breakdown, Employee usage
     * Time Complexity: O(n) where n = number of trips
     */
    public ClientReport generateClientReport(UUID clientId, YearMonth reportMonth) {
        ClientReport report = new ClientReport();
        report.setClientId(clientId);
        report.setReportMonth(reportMonth);
        report.setGeneratedAt(LocalDateTime.now());
        report.setReportId(UUID.randomUUID());
        
        // Summary data (in production, fetch from database/services)
        report.setTotalTrips(150);
        report.setTotalDistance(new BigDecimal("2500.50"));
        report.setTotalCost(new BigDecimal("75000.00"));
        report.setTotalTax(new BigDecimal("13500.00"));
        report.setGrandTotal(new BigDecimal("88500.00"));
        report.setActiveEmployees(25);
        report.setActiveVendors(3);
        
        // Vendor-wise breakdown
        List<VendorBreakdown> vendorBreakdowns = new ArrayList<>();
        
        VendorBreakdown vendor1 = new VendorBreakdown();
        vendor1.setVendorId(UUID.randomUUID());
        vendor1.setVendorName("Ola Cabs");
        vendor1.setTripCount(60);
        vendor1.setTotalDistance(new BigDecimal("950.25"));
        vendor1.setBillingModel("TRIP");
        vendor1.setAmount(new BigDecimal("28500.00"));
        vendorBreakdowns.add(vendor1);
        
        VendorBreakdown vendor2 = new VendorBreakdown();
        vendor2.setVendorId(UUID.randomUUID());
        vendor2.setVendorName("Uber India");
        vendor2.setTripCount(70);
        vendor2.setTotalDistance(new BigDecimal("1050.00"));
        vendor2.setBillingModel("PACKAGE");
        vendor2.setAmount(new BigDecimal("25000.00"));
        vendorBreakdowns.add(vendor2);
        
        VendorBreakdown vendor3 = new VendorBreakdown();
        vendor3.setVendorId(UUID.randomUUID());
        vendor3.setVendorName("Rapido Bike Taxi");
        vendor3.setTripCount(20);
        vendor3.setTotalDistance(new BigDecimal("500.25"));
        vendor3.setBillingModel("HYBRID");
        vendor3.setAmount(new BigDecimal("21500.00"));
        vendorBreakdowns.add(vendor3);
        
        report.setVendorBreakdown(vendorBreakdowns);
        
        // Department-wise usage
        Map<String, Integer> departmentUsage = new HashMap<>();
        departmentUsage.put("Engineering", 50);
        departmentUsage.put("Operations", 40);
        departmentUsage.put("HR", 30);
        departmentUsage.put("Sales", 30);
        report.setDepartmentWiseUsage(departmentUsage);
        
        report.setReportStatus("GENERATED");
        report.setAuditTrail("Generated by system at " + LocalDateTime.now());
        
        return report;
    }
    
    /**
     * Generate Vendor Report
     * Shows: Payable amount, Trip details, Incentives, Payment breakdown
     */
    public VendorReport generateVendorReport(UUID vendorId, UUID clientId, YearMonth reportMonth) {
        VendorReport report = new VendorReport();
        report.setVendorId(vendorId);
        report.setClientId(clientId);
        report.setReportMonth(reportMonth);
        report.setGeneratedAt(LocalDateTime.now());
        report.setReportId(UUID.randomUUID());
        
        // Payment summary
        report.setTotalTripsCompleted(70);
        report.setTotalDistanceKm(new BigDecimal("1050.00"));
        report.setBillingModelType("PACKAGE");
        report.setBasePackageAmount(new BigDecimal("25000.00"));
        report.setOverageCharges(new BigDecimal("2500.00"));
        report.setIncentiveAmount(new BigDecimal("1500.00"));
        report.setTotalPayable(new BigDecimal("29000.00"));
        report.setServiceRating(4.7);
        
        // Trip statistics
        report.setAverageDistancePerTrip(new BigDecimal("15.0"));
        report.setAverageDurationPerTrip(new BigDecimal("1.2"));
        report.setPeakHourTrips(15);
        report.setOffPeakTrips(55);
        
        // Payment details
        report.setPaymentTerms("Net 30 Days");
        report.setPaymentDueDate(LocalDateTime.now().plusDays(30));
        report.setPaymentStatus("PENDING");
        
        // Detailed trip list (top 10 for preview)
        List<TripDetail> tripDetails = new ArrayList<>();
        for (int i = 1; i <= 10; i++) {
            TripDetail trip = new TripDetail();
            trip.setTripId(UUID.randomUUID());
            trip.setTripDate(reportMonth.atDay(i).atTime(9, 0));
            trip.setEmployeeName("Employee " + i);
            trip.setDistance(new BigDecimal("15.0"));
            trip.setDuration(new BigDecimal("1.2"));
            trip.setAmount(new BigDecimal("350.00"));
            tripDetails.add(trip);
        }
        report.setTripDetails(tripDetails);
        
        report.setReportNotes("All trips completed successfully. Excellent service rating!");
        
        return report;
    }
    
    /**
     * Generate Employee Report
     * Shows: Total trips, Incentives earned, Monthly summary
     */
    public EmployeeReport generateEmployeeReport(UUID employeeId, UUID clientId, YearMonth reportMonth) {
        EmployeeReport report = new EmployeeReport();
        report.setEmployeeId(employeeId);
        report.setClientId(clientId);
        report.setReportMonth(reportMonth);
        report.setGeneratedAt(LocalDateTime.now());
        report.setReportId(UUID.randomUUID());
        
        // Trip summary
        report.setTotalTrips(22);
        report.setTotalDistanceKm(new BigDecimal("305.75"));
        report.setTotalHours(new BigDecimal("26.4"));
        report.setAverageDistance(new BigDecimal("13.9"));
        
        // Incentive summary
        report.setExtraHourIncentive(new BigDecimal("750.00")); // 3 hours × ₹250
        report.setLateNightTripIncentive(new BigDecimal("300.00")); // 2 trips × ₹150
        report.setWeekendTripIncentive(new BigDecimal("400.00")); // 2 trips × ₹200
        report.setTotalIncentiveEarned(new BigDecimal("1450.00"));
        
        // Trip breakdown
        report.setMorningTrips(11);
        report.setEveningTrips(8);
        report.setLateNightTrips(2);
        report.setWeekendTrips(2);
        
        // Monthly trend
        Map<String, Integer> weeklyTrips = new HashMap<>();
        weeklyTrips.put("Week 1", 6);
        weeklyTrips.put("Week 2", 5);
        weeklyTrips.put("Week 3", 6);
        weeklyTrips.put("Week 4", 5);
        report.setWeeklyTripBreakdown(weeklyTrips);
        
        // Top routes
        List<String> topRoutes = Arrays.asList(
            "Whitefield → Office (8 trips)",
            "HSR Layout → Office (6 trips)",
            "Koramangala → Office (5 trips)"
        );
        report.setTopRoutes(topRoutes);
        
        report.setIncentivePayoutStatus("PENDING");
        report.setIncentivePayoutDate(LocalDateTime.now().plusDays(5));
        report.setReportNotes("Great usage! You've earned extra incentives for late-night and weekend trips.");
        
        return report;
    }
    
    /**
     * Generate Consolidated Monthly Report
     * Master report combining all entities
     */
    public ConsolidatedReport generateConsolidatedReport(YearMonth reportMonth) {
        ConsolidatedReport report = new ConsolidatedReport();
        report.setReportMonth(reportMonth);
        report.setGeneratedAt(LocalDateTime.now());
        report.setReportId(UUID.randomUUID());
        
        // Platform-wide statistics
        report.setTotalClients(4);
        report.setTotalVendors(5);
        report.setTotalEmployees(150);
        report.setTotalTrips(450);
        report.setTotalRevenue(new BigDecimal("250000.00"));
        report.setTotalIncentivesPaid(new BigDecimal("35000.00"));
        
        // Top performing client
        report.setTopClient("Amazon India - 150 trips");
        report.setTopVendor("Uber India - 120 trips");
        
        // Financial summary
        report.setTotalBilled(new BigDecimal("250000.00"));
        report.setTotalCollected(new BigDecimal("200000.00"));
        report.setTotalPending(new BigDecimal("50000.00"));
        
        return report;
    }
    
    // Inner classes for report DTOs
    public static class ClientReport {
        private UUID reportId;
        private UUID clientId;
        private YearMonth reportMonth;
        private LocalDateTime generatedAt;
        private Integer totalTrips;
        private BigDecimal totalDistance;
        private BigDecimal totalCost;
        private BigDecimal totalTax;
        private BigDecimal grandTotal;
        private Integer activeEmployees;
        private Integer activeVendors;
        private List<VendorBreakdown> vendorBreakdown;
        private Map<String, Integer> departmentWiseUsage;
        private String reportStatus;
        private String auditTrail;
        
        // Getters and Setters
        public UUID getReportId() { return reportId; }
        public void setReportId(UUID reportId) { this.reportId = reportId; }
        public UUID getClientId() { return clientId; }
        public void setClientId(UUID clientId) { this.clientId = clientId; }
        public YearMonth getReportMonth() { return reportMonth; }
        public void setReportMonth(YearMonth reportMonth) { this.reportMonth = reportMonth; }
        public LocalDateTime getGeneratedAt() { return generatedAt; }
        public void setGeneratedAt(LocalDateTime generatedAt) { this.generatedAt = generatedAt; }
        public Integer getTotalTrips() { return totalTrips; }
        public void setTotalTrips(Integer totalTrips) { this.totalTrips = totalTrips; }
        public BigDecimal getTotalDistance() { return totalDistance; }
        public void setTotalDistance(BigDecimal totalDistance) { this.totalDistance = totalDistance; }
        public BigDecimal getTotalCost() { return totalCost; }
        public void setTotalCost(BigDecimal totalCost) { this.totalCost = totalCost; }
        public BigDecimal getTotalTax() { return totalTax; }
        public void setTotalTax(BigDecimal totalTax) { this.totalTax = totalTax; }
        public BigDecimal getGrandTotal() { return grandTotal; }
        public void setGrandTotal(BigDecimal grandTotal) { this.grandTotal = grandTotal; }
        public Integer getActiveEmployees() { return activeEmployees; }
        public void setActiveEmployees(Integer activeEmployees) { this.activeEmployees = activeEmployees; }
        public Integer getActiveVendors() { return activeVendors; }
        public void setActiveVendors(Integer activeVendors) { this.activeVendors = activeVendors; }
        public List<VendorBreakdown> getVendorBreakdown() { return vendorBreakdown; }
        public void setVendorBreakdown(List<VendorBreakdown> vendorBreakdown) { this.vendorBreakdown = vendorBreakdown; }
        public Map<String, Integer> getDepartmentWiseUsage() { return departmentWiseUsage; }
        public void setDepartmentWiseUsage(Map<String, Integer> departmentWiseUsage) { this.departmentWiseUsage = departmentWiseUsage; }
        public String getReportStatus() { return reportStatus; }
        public void setReportStatus(String reportStatus) { this.reportStatus = reportStatus; }
        public String getAuditTrail() { return auditTrail; }
        public void setAuditTrail(String auditTrail) { this.auditTrail = auditTrail; }
    }
    
    public static class VendorBreakdown {
        private UUID vendorId;
        private String vendorName;
        private Integer tripCount;
        private BigDecimal totalDistance;
        private String billingModel;
        private BigDecimal amount;
        
        // Getters and Setters
        public UUID getVendorId() { return vendorId; }
        public void setVendorId(UUID vendorId) { this.vendorId = vendorId; }
        public String getVendorName() { return vendorName; }
        public void setVendorName(String vendorName) { this.vendorName = vendorName; }
        public Integer getTripCount() { return tripCount; }
        public void setTripCount(Integer tripCount) { this.tripCount = tripCount; }
        public BigDecimal getTotalDistance() { return totalDistance; }
        public void setTotalDistance(BigDecimal totalDistance) { this.totalDistance = totalDistance; }
        public String getBillingModel() { return billingModel; }
        public void setBillingModel(String billingModel) { this.billingModel = billingModel; }
        public BigDecimal getAmount() { return amount; }
        public void setAmount(BigDecimal amount) { this.amount = amount; }
    }
    
    public static class VendorReport {
        private UUID reportId;
        private UUID vendorId;
        private UUID clientId;
        private YearMonth reportMonth;
        private LocalDateTime generatedAt;
        private Integer totalTripsCompleted;
        private BigDecimal totalDistanceKm;
        private String billingModelType;
        private BigDecimal basePackageAmount;
        private BigDecimal overageCharges;
        private BigDecimal incentiveAmount;
        private BigDecimal totalPayable;
        private Double serviceRating;
        private BigDecimal averageDistancePerTrip;
        private BigDecimal averageDurationPerTrip;
        private Integer peakHourTrips;
        private Integer offPeakTrips;
        private String paymentTerms;
        private LocalDateTime paymentDueDate;
        private String paymentStatus;
        private List<TripDetail> tripDetails;
        private String reportNotes;
        
        // Getters and Setters (abbreviated for brevity)
        public UUID getReportId() { return reportId; }
        public void setReportId(UUID reportId) { this.reportId = reportId; }
        public UUID getVendorId() { return vendorId; }
        public void setVendorId(UUID vendorId) { this.vendorId = vendorId; }
        public UUID getClientId() { return clientId; }
        public void setClientId(UUID clientId) { this.clientId = clientId; }
        public YearMonth getReportMonth() { return reportMonth; }
        public void setReportMonth(YearMonth reportMonth) { this.reportMonth = reportMonth; }
        public LocalDateTime getGeneratedAt() { return generatedAt; }
        public void setGeneratedAt(LocalDateTime generatedAt) { this.generatedAt = generatedAt; }
        public Integer getTotalTripsCompleted() { return totalTripsCompleted; }
        public void setTotalTripsCompleted(Integer totalTripsCompleted) { this.totalTripsCompleted = totalTripsCompleted; }
        public BigDecimal getTotalDistanceKm() { return totalDistanceKm; }
        public void setTotalDistanceKm(BigDecimal totalDistanceKm) { this.totalDistanceKm = totalDistanceKm; }
        public String getBillingModelType() { return billingModelType; }
        public void setBillingModelType(String billingModelType) { this.billingModelType = billingModelType; }
        public BigDecimal getBasePackageAmount() { return basePackageAmount; }
        public void setBasePackageAmount(BigDecimal basePackageAmount) { this.basePackageAmount = basePackageAmount; }
        public BigDecimal getOverageCharges() { return overageCharges; }
        public void setOverageCharges(BigDecimal overageCharges) { this.overageCharges = overageCharges; }
        public BigDecimal getIncentiveAmount() { return incentiveAmount; }
        public void setIncentiveAmount(BigDecimal incentiveAmount) { this.incentiveAmount = incentiveAmount; }
        public BigDecimal getTotalPayable() { return totalPayable; }
        public void setTotalPayable(BigDecimal totalPayable) { this.totalPayable = totalPayable; }
        public Double getServiceRating() { return serviceRating; }
        public void setServiceRating(Double serviceRating) { this.serviceRating = serviceRating; }
        public BigDecimal getAverageDistancePerTrip() { return averageDistancePerTrip; }
        public void setAverageDistancePerTrip(BigDecimal averageDistancePerTrip) { this.averageDistancePerTrip = averageDistancePerTrip; }
        public BigDecimal getAverageDurationPerTrip() { return averageDurationPerTrip; }
        public void setAverageDurationPerTrip(BigDecimal averageDurationPerTrip) { this.averageDurationPerTrip = averageDurationPerTrip; }
        public Integer getPeakHourTrips() { return peakHourTrips; }
        public void setPeakHourTrips(Integer peakHourTrips) { this.peakHourTrips = peakHourTrips; }
        public Integer getOffPeakTrips() { return offPeakTrips; }
        public void setOffPeakTrips(Integer offPeakTrips) { this.offPeakTrips = offPeakTrips; }
        public String getPaymentTerms() { return paymentTerms; }
        public void setPaymentTerms(String paymentTerms) { this.paymentTerms = paymentTerms; }
        public LocalDateTime getPaymentDueDate() { return paymentDueDate; }
        public void setPaymentDueDate(LocalDateTime paymentDueDate) { this.paymentDueDate = paymentDueDate; }
        public String getPaymentStatus() { return paymentStatus; }
        public void setPaymentStatus(String paymentStatus) { this.paymentStatus = paymentStatus; }
        public List<TripDetail> getTripDetails() { return tripDetails; }
        public void setTripDetails(List<TripDetail> tripDetails) { this.tripDetails = tripDetails; }
        public String getReportNotes() { return reportNotes; }
        public void setReportNotes(String reportNotes) { this.reportNotes = reportNotes; }
    }
    
    public static class TripDetail {
        private UUID tripId;
        private LocalDateTime tripDate;
        private String employeeName;
        private BigDecimal distance;
        private BigDecimal duration;
        private BigDecimal amount;
        
        // Getters and Setters
        public UUID getTripId() { return tripId; }
        public void setTripId(UUID tripId) { this.tripId = tripId; }
        public LocalDateTime getTripDate() { return tripDate; }
        public void setTripDate(LocalDateTime tripDate) { this.tripDate = tripDate; }
        public String getEmployeeName() { return employeeName; }
        public void setEmployeeName(String employeeName) { this.employeeName = employeeName; }
        public BigDecimal getDistance() { return distance; }
        public void setDistance(BigDecimal distance) { this.distance = distance; }
        public BigDecimal getDuration() { return duration; }
        public void setDuration(BigDecimal duration) { this.duration = duration; }
        public BigDecimal getAmount() { return amount; }
        public void setAmount(BigDecimal amount) { this.amount = amount; }
    }
    
    public static class EmployeeReport {
        private UUID reportId;
        private UUID employeeId;
        private UUID clientId;
        private YearMonth reportMonth;
        private LocalDateTime generatedAt;
        private Integer totalTrips;
        private BigDecimal totalDistanceKm;
        private BigDecimal totalHours;
        private BigDecimal averageDistance;
        private BigDecimal extraHourIncentive;
        private BigDecimal lateNightTripIncentive;
        private BigDecimal weekendTripIncentive;
        private BigDecimal totalIncentiveEarned;
        private Integer morningTrips;
        private Integer eveningTrips;
        private Integer lateNightTrips;
        private Integer weekendTrips;
        private Map<String, Integer> weeklyTripBreakdown;
        private List<String> topRoutes;
        private String incentivePayoutStatus;
        private LocalDateTime incentivePayoutDate;
        private String reportNotes;
        
        // Getters and Setters (abbreviated for brevity)
        public UUID getReportId() { return reportId; }
        public void setReportId(UUID reportId) { this.reportId = reportId; }
        public UUID getEmployeeId() { return employeeId; }
        public void setEmployeeId(UUID employeeId) { this.employeeId = employeeId; }
        public UUID getClientId() { return clientId; }
        public void setClientId(UUID clientId) { this.clientId = clientId; }
        public YearMonth getReportMonth() { return reportMonth; }
        public void setReportMonth(YearMonth reportMonth) { this.reportMonth = reportMonth; }
        public LocalDateTime getGeneratedAt() { return generatedAt; }
        public void setGeneratedAt(LocalDateTime generatedAt) { this.generatedAt = generatedAt; }
        public Integer getTotalTrips() { return totalTrips; }
        public void setTotalTrips(Integer totalTrips) { this.totalTrips = totalTrips; }
        public BigDecimal getTotalDistanceKm() { return totalDistanceKm; }
        public void setTotalDistanceKm(BigDecimal totalDistanceKm) { this.totalDistanceKm = totalDistanceKm; }
        public BigDecimal getTotalHours() { return totalHours; }
        public void setTotalHours(BigDecimal totalHours) { this.totalHours = totalHours; }
        public BigDecimal getAverageDistance() { return averageDistance; }
        public void setAverageDistance(BigDecimal averageDistance) { this.averageDistance = averageDistance; }
        public BigDecimal getExtraHourIncentive() { return extraHourIncentive; }
        public void setExtraHourIncentive(BigDecimal extraHourIncentive) { this.extraHourIncentive = extraHourIncentive; }
        public BigDecimal getLateNightTripIncentive() { return lateNightTripIncentive; }
        public void setLateNightTripIncentive(BigDecimal lateNightTripIncentive) { this.lateNightTripIncentive = lateNightTripIncentive; }
        public BigDecimal getWeekendTripIncentive() { return weekendTripIncentive; }
        public void setWeekendTripIncentive(BigDecimal weekendTripIncentive) { this.weekendTripIncentive = weekendTripIncentive; }
        public BigDecimal getTotalIncentiveEarned() { return totalIncentiveEarned; }
        public void setTotalIncentiveEarned(BigDecimal totalIncentiveEarned) { this.totalIncentiveEarned = totalIncentiveEarned; }
        public Integer getMorningTrips() { return morningTrips; }
        public void setMorningTrips(Integer morningTrips) { this.morningTrips = morningTrips; }
        public Integer getEveningTrips() { return eveningTrips; }
        public void setEveningTrips(Integer eveningTrips) { this.eveningTrips = eveningTrips; }
        public Integer getLateNightTrips() { return lateNightTrips; }
        public void setLateNightTrips(Integer lateNightTrips) { this.lateNightTrips = lateNightTrips; }
        public Integer getWeekendTrips() { return weekendTrips; }
        public void setWeekendTrips(Integer weekendTrips) { this.weekendTrips = weekendTrips; }
        public Map<String, Integer> getWeeklyTripBreakdown() { return weeklyTripBreakdown; }
        public void setWeeklyTripBreakdown(Map<String, Integer> weeklyTripBreakdown) { this.weeklyTripBreakdown = weeklyTripBreakdown; }
        public List<String> getTopRoutes() { return topRoutes; }
        public void setTopRoutes(List<String> topRoutes) { this.topRoutes = topRoutes; }
        public String getIncentivePayoutStatus() { return incentivePayoutStatus; }
        public void setIncentivePayoutStatus(String incentivePayoutStatus) { this.incentivePayoutStatus = incentivePayoutStatus; }
        public LocalDateTime getIncentivePayoutDate() { return incentivePayoutDate; }
        public void setIncentivePayoutDate(LocalDateTime incentivePayoutDate) { this.incentivePayoutDate = incentivePayoutDate; }
        public String getReportNotes() { return reportNotes; }
        public void setReportNotes(String reportNotes) { this.reportNotes = reportNotes; }
    }
    
    public static class ConsolidatedReport {
        private UUID reportId;
        private YearMonth reportMonth;
        private LocalDateTime generatedAt;
        private Integer totalClients;
        private Integer totalVendors;
        private Integer totalEmployees;
        private Integer totalTrips;
        private BigDecimal totalRevenue;
        private BigDecimal totalIncentivesPaid;
        private String topClient;
        private String topVendor;
        private BigDecimal totalBilled;
        private BigDecimal totalCollected;
        private BigDecimal totalPending;
        
        // Getters and Setters (abbreviated)
        public UUID getReportId() { return reportId; }
        public void setReportId(UUID reportId) { this.reportId = reportId; }
        public YearMonth getReportMonth() { return reportMonth; }
        public void setReportMonth(YearMonth reportMonth) { this.reportMonth = reportMonth; }
        public LocalDateTime getGeneratedAt() { return generatedAt; }
        public void setGeneratedAt(LocalDateTime generatedAt) { this.generatedAt = generatedAt; }
        public Integer getTotalClients() { return totalClients; }
        public void setTotalClients(Integer totalClients) { this.totalClients = totalClients; }
        public Integer getTotalVendors() { return totalVendors; }
        public void setTotalVendors(Integer totalVendors) { this.totalVendors = totalVendors; }
        public Integer getTotalEmployees() { return totalEmployees; }
        public void setTotalEmployees(Integer totalEmployees) { this.totalEmployees = totalEmployees; }
        public Integer getTotalTrips() { return totalTrips; }
        public void setTotalTrips(Integer totalTrips) { this.totalTrips = totalTrips; }
        public BigDecimal getTotalRevenue() { return totalRevenue; }
        public void setTotalRevenue(BigDecimal totalRevenue) { this.totalRevenue = totalRevenue; }
        public BigDecimal getTotalIncentivesPaid() { return totalIncentivesPaid; }
        public void setTotalIncentivesPaid(BigDecimal totalIncentivesPaid) { this.totalIncentivesPaid = totalIncentivesPaid; }
        public String getTopClient() { return topClient; }
        public void setTopClient(String topClient) { this.topClient = topClient; }
        public String getTopVendor() { return topVendor; }
        public void setTopVendor(String topVendor) { this.topVendor = topVendor; }
        public BigDecimal getTotalBilled() { return totalBilled; }
        public void setTotalBilled(BigDecimal totalBilled) { this.totalBilled = totalBilled; }
        public BigDecimal getTotalCollected() { return totalCollected; }
        public void setTotalCollected(BigDecimal totalCollected) { this.totalCollected = totalCollected; }
        public BigDecimal getTotalPending() { return totalPending; }
        public void setTotalPending(BigDecimal totalPending) { this.totalPending = totalPending; }
    }
}

